const lectorArr = [
    {
        lectorImg: "/images/lectors/terezav.png",
        lectorName: "Tereza Vaňková",
        lectorJob: "ReactGirls zakladatelka",
        lectorCompany: "frontend developer v Avast",
        lectorLinkedIn: "https://www.linkedin.com/in/tereza-vankova",
    },
    {
        lectorImg: "/images/lectors/braňo.jpeg",
        lectorName: "Branislav Benčík",
        lectorJob: "UX Designer",
        lectorCompany: "v Applifting Česko",
        lectorLinkedIn: "https://cz.linkedin.com/in/branislavbencik",
    },
    {
        lectorImg: "/images/lectors/zuzkastav-1.png",
        lectorName: "Zuzana Stavjaňová",
        lectorJob: "React developer",
        lectorCompany: "v Sinch s.r.o",
        lectorLinkedIn: "https://www.linkedin.com/today/author/zuzanastavjanova",  
    },
    {
        lectorImg: "/images/lectors/simca.jpg",
        lectorName: "Simona Töröková",
        lectorJob: "Data Analyst/Scientist",
        lectorCompany: "v DataSentics",
        lectorLinkedIn: "https://www.linkedin.com/simona-t%C3%B6r%C3%B6kov%C3%A1-31baa211a/",
    },
    {
        lectorImg: "/images/lectors/richard.jpg",
        lectorName: "Riki Fridrich",
        lectorJob: "vývojář",
        lectorCompany: "v Mall.cz",
        lectorLinkedIn: "https://www.linkedin.com/in/fczbkk",
    },   
    {
        lectorImg: "/images/lectors/terkam.jpeg",
        lectorName: "Tereza Macháčková",
        lectorJob: "People & Tech Products",
        lectorCompany: "v Credo Ventures",
        lectorLinkedIn: "https://www.linkedin.com/in/tereza-mach%C3%A1%C4%8Dkov%C3%A1-29783a9a/",
    },
    {
        lectorImg: "/images/lectors/martinh.jpg",
        lectorName: "Martin Hochel",
        lectorJob: "Vývojář v Microsoft",
        lectorCompany: "zakladatel ngParty",
        lectorLinkedIn: "https://www.linkedin.com/in/hochelmartin/",
    },
    {
        lectorImg: "/images/lectors/karold.jpg",
        lectorName: "Karol Danko",
        lectorJob: "CTO",
        lectorCompany: "v OAK'S LAB",
        lectorLinkedIn: "https://www.linkedin.com/in/karoldanko/",
    },
    {
        lectorImg: "/images/lectors/pavelc.jpg",
        lectorName: "Pavel Cvetler",
        lectorJob: "Vývojář a team lead",
        lectorCompany: "v Livesport",
        lectorLinkedIn: "https://www.linkedin.com/in/pavel-cvetler-36485bb4/",
    },
    {
        lectorImg: "/images/lectors/zuzkapes-300x300.jpg",
        lectorName: "Zuzana Pešková",
        lectorJob: "HR",
        lectorCompany: "v Livesport",
        lectorLinkedIn: "https://www.linkedin.com/in/zuzka-peskova/",
    },
    {
        lectorImg: "/images/lectors/romansch.jpg",
        lectorName: "Roman Schejbal",
        lectorJob: "programátor",
        lectorCompany: "v HomeWerk",
        lectorLinkedIn: "https://www.linkedin.com/in/roman-schejbal-b71b3447/",
    },
    {
        lectorImg: "/images/lectors/hanahaber-300x300.jpg",
        lectorName: "Hana Habermannová",
        lectorJob: "CEO a Company Director",
        lectorCompany: " v PPC Bee",
        lectorLinkedIn: "https://www.linkedin.com/in/hanahabermannova/",
    },
    {
        lectorImg: "/images/lectors/lenak.jpg",
        lectorName: "Lena Kirichok",
        lectorJob: "Backend Developer",
        lectorCompany: "v Zásilkovna s.r.o",
        lectorLinkedIn: "https://www.linkedin.com/in/lena-k-14b891aa/",
    },
    {
        lectorImg: "/images/lectors/marekv.jpg",
        lectorName: "Marek Velas",
        lectorJob: "Zakladatel",
        lectorCompany: "EDUpunk",
        lectorLinkedIn: "https://www.linkedin.com/in/marek-velas/",
    },
    {
        lectorImg: "/images/lectors/petraz-300x300.jpg",
        lectorName: "Petra Zárubová",
        lectorJob: "lektor osobního rozvoje",
        lectorCompany: "",
        lectorLinkedIn: "https://www.linkedin.com/in/petra-gasek-zarubova/",
    },
    {
        lectorImg: "/images/lectors/ondrejk.jpg",
        lectorName: "Ondřej Kučera",
        lectorJob: "senior consultant",
        lectorCompany: "v Unicorn systems",
        lectorLinkedIn: "https://www.linkedin.com/in/ond%C5%99ej-ku%C4%8Dera-9410167/",
    },
    {
        lectorImg: "/images/lectors/kamilam.jpg",
        lectorName: "Kamila Macháčová",
        lectorJob: "HR",
        lectorCompany: "v Applifting Česko",
        lectorLinkedIn: "https://www.linkedin.com/in/kamilamach%C3%A1%C4%8Dov%C3%A1/",
    },
    {
        lectorImg: "/images/lectors/pavels.jpg",
        lectorName: "Pavel Šuraba",
        lectorJob: "Frontend vývojář",
        lectorCompany: "v Productboardu",
        lectorLinkedIn: "https://www.linkedin.com/in/pavel-suraba/?originalSubdomain=cz",
    },
    {
        lectorImg: "/images/lectors/kirillb.jpg",
        lectorName: "Kirill Bunin",
        lectorJob: "IT Consultant",
        lectorCompany: "programátor ve Vue.js",
        lectorLinkedIn: "https://www.linkedin.com/in/kirillbunin/?originalSubdomain=cz",
    },
    {
        lectorImg: "/images/lectors/lukasv.jpg",
        lectorName: "Lukáš Valenta",
        lectorJob: "Vývojář",
        lectorCompany: "v Applifting",
        lectorLinkedIn: "https://www.linkedin.com/in/luk%C3%A1%C5%A1-valenta-313b328a/",
    },
]

export default lectorArr;