const lectorArr = [
    {
        lectorInterest: "Workshop | Akademie | Mentoring",
        lectorImg: "/images/lectors/braňo.jpeg",
        lectorName: "Branislav Benčík",
        lectorInfo: "Braňo nás provede kopletními základy kódování v HTML a CSS.",
        lectorJob: "UX Designer",
        lectorCompany: "v Applifting Česko",
        lectorLinkedIn: "https://cz.linkedin.com/in/branislavbencik",
    },
    {
        lectorInterest: "Workshop | Akademie ",
        lectorImg: "/images/lectors/zuzkastav-1.png",
        lectorName: "Zuzana Stavjaňová",
        lectorInfo: "Zuzka si pro Vás připravila lekci Reactu přizpůsobenou začátečníkům.",
        lectorJob: "React developer",
        lectorCompany: "v Sinch s.r.o",
        lectorLinkedIn: "https://www.linkedin.com/today/author/zuzanastavjanova",  
    },
    {
        lectorInterest: "Workshop | Akademie ",
        lectorImg: "/images/lectors/richard.jpg",
        lectorName: "Riki Fridrich",
        lectorInfo: "Riki je guru JavaScriptu a má mnohaleté zkušenosti s přednášením a lektorováním.",
        lectorJob: "vývojář",
        lectorCompany: "v Mall.cz",
        lectorLinkedIn: "https://www.linkedin.com/in/fczbkk",
    },
    {
        lectorInterest: "Workshop | Akademie ",
        lectorImg: "/images/lectors/simca.jpg",
        lectorName: "Simona Töröková",
        lectorInfo: "",
        lectorJob: "Data Analyst/Scientist",
        lectorCompany: "v DataSentics",
        lectorLinkedIn: "https://www.linkedin.com/in/simona-t%C3%B6r%C3%B6kov%C3%A1-31baa211a/",
    },
    {
        lectorInterest: "Workshop | Akademie ",
        lectorImg: "/images/lectors/martinh.jpg",
        lectorName: "Martin Hochel",
        lectorInfo: "",
        lectorJob: "Principal Engineer",
        lectorCompany: "v ngParty",
        lectorLinkedIn: "https://www.linkedin.com/in/hochelmartin/",
    },
    {
        lectorInterest: "Workshop | Akademie ",
        lectorImg: "/images/lectors/terkam.jpeg",
        lectorName: "Tereza Macháčková",
        lectorInfo: "",
        lectorJob: "People & Tech Products",
        lectorCompany: "v Credo Ventures",
        lectorLinkedIn: "https://www.linkedin.com/in/tereza-mach%C3%A1%C4%8Dkov%C3%A1-29783a9a/",
    },
    {
        lectorInterest: "Workshop | Akademie ",
        lectorImg: "/images/lectors/karold.jpg",
        lectorName: "Karol Danko",
        lectorInfo: "",
        lectorJob: "CTO",
        lectorCompany: "v OAK'S LAB",
        lectorLinkedIn: "https://www.linkedin.com/in/karoldanko/",
    },
    {
        lectorInterest: "Workshop | Akademie ",
        lectorImg: "/images/lectors/pavelc.jpg",
        lectorName: "Pavel Cvetler",
        lectorInfo: "",
        lectorJob: "programátor",
        lectorCompany: "v Livesport",
        lectorLinkedIn: "https://www.linkedin.com/in/pavel-cvetler-36485bb4/",
    },
    {
        lectorInterest: "Workshop | Akademie ",
        lectorImg: "/images/lectors/zuzkapes-300x300.jpg",
        lectorName: "Zuzana Pešková",
        lectorInfo: "",
        lectorJob: "HR",
        lectorCompany: "v Livesport",
        lectorLinkedIn: "https://www.linkedin.com/in/zuzka-peskova/",
    },
    {
        lectorInterest: "Workshop | Akademie ",
        lectorImg: "/images/lectors/juliach-300x300.jpg",
        lectorName: "Julia Christodoulou",
        lectorInfo: "",
        lectorJob: "Mentor",
        lectorCompany: "ve Femme Palette",
        lectorLinkedIn: "https://www.linkedin.com/in/christodouloujulia/",
    },
    {
        lectorInterest: "Workshop | Akademie ",
        lectorImg: "/images/lectors/romansch.jpg",
        lectorName: "Roman Schejbal",
        lectorInfo: "",
        lectorJob: "programátor",
        lectorCompany: "ve HomeWerk",
        lectorLinkedIn: "https://www.linkedin.com/in/roman-schejbal-b71b3447/",
    },
    {
        lectorInterest: "Workshop | Akademie ",
        lectorImg: "/images/lectors/hanahaber-300x300.jpg",
        lectorName: "Hana Habermannová",
        lectorInfo: "",
        lectorJob: "CEO a Company Director",
        lectorCompany: " v PPC Bee",
        lectorLinkedIn: "https://www.linkedin.com/in/hanahabermannova/",
    },
    {
        lectorInterest: "Workshop | Akademie ",
        lectorImg: "/images/lectors/lenak.jpg",
        lectorName: "Lena Kirichok",
        lectorInfo: "",
        lectorJob: "Backend Developer",
        lectorCompany: "v Zásilkovna s.r.o",
        lectorLinkedIn: "https://www.linkedin.com/in/lena-k-14b891aa/",
    },
    {
        lectorInterest: "Workshop | Akademie ",
        lectorImg: "/images/lectors/marekv.jpg",
        lectorName: "Marek Velas",
        lectorInfo: "",
        lectorJob: "Zakladatel",
        lectorCompany: "EDUpunk",
        lectorLinkedIn: "https://www.linkedin.com/in/marek-velas/",
    },
    {
        lectorInterest: "Workshop | Akademie ",
        lectorImg: "/images/lectors/marta.jpg",
        lectorName: "Martina Plocová",
        lectorInfo: "",
        lectorJob: "",
        lectorCompany: "",
    },
    {
        lectorInterest: "Workshop | Akademie ",
        lectorImg: "/images/lectors/petraz-300x300.jpg",
        lectorName: "Petra Zárubová",
        lectorInfo: "",
        lectorJob: "lektor",
        lectorCompany: "v top vision s.r.o",
        lectorLinkedIn: "https://www.linkedin.com/in/petra-gasek-zarubova/",
    },
]

export default lectorArr;