export { default as Navbar} from './Navbar/Navbar';
export { default as Hero } from './reusable/Hero/Hero';
export { default as Sponzor} from './Sponzor/Sponzor';
export { default as Product} from './Product/Product';
export { default as Newsletter} from './Newsletter/Newsletter';
export { default as Lector} from './Lector/Lector';
export { default as Footer} from './Footer/Footer';
export { default as ContactHero} from './ContactHero/ContactHero';
export { default as ContactPeople} from './ContactPeople/ContactPeople';
export { default as ContactBank} from './ContactBank/ContactBank';
export { default as References} from './References/References';
export { default as Info} from './reusable/Info/Info';
export { default as InfoCards} from './reusable/InfoCards/InfoCards';
export { default as Student} from './reusable/Student/Student';
export { default as Price} from './Price/Price';
export { default as Questions} from './Questions/Questions';
export { default as Program} from './Program/Program';
